import {
	MediaCenterAlbum,
	MediaCenterPhoto,
	MediaCenterStats,
	MediaCenterContributor,
	LiveFeedPhoto,
	PhotoBoothPhoto,
} from "./types";

export const MOCK_ALBUMS: MediaCenterAlbum[] = [
	{
		id: "1",
		slug: "wedding-main",
		name: "Wedding",
		description: "Main wedding event album",
		coverPhotoUrl: null,
		photoCount: 0,
		videoCount: 0,
		subAlbumCount: 1,
		maxPhotosPerGuest: 15,
		allowDownloads: true,
		requireApproval: false,
		isActive: true,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		parentAlbumId: null,
		eventId: "event-1",
	},
	{
		id: "2",
		slug: "ceremony-sub",
		name: "Ceremony",
		description: "Wedding ceremony photos",
		coverPhotoUrl: "https://picsum.photos/400/300?random=1",
		photoCount: 45,
		videoCount: 3,
		subAlbumCount: 0,
		maxPhotosPerGuest: 10,
		allowDownloads: true,
		requireApproval: true,
		isActive: true,
		createdAt: new Date(Date.now() - 86400000).toISOString(),
		updatedAt: new Date().toISOString(),
		parentAlbumId: "1",
		eventId: "event-1",
	},
];

export const MOCK_PHOTOS: MediaCenterPhoto[] = [
	{
		id: "1",
		slug: "photo-1",
		url: "https://picsum.photos/800/600?random=1",
		thumbnailUrl: "https://picsum.photos/400/300?random=1",
		title: "Wedding Ceremony",
		tags: ["ceremony", "wedding", "bride", "groom"],
		uploadedBy: {
			id: "user-1",
			name: "John Doe",
			avatar: "https://ui-avatars.com/api/?name=John+Doe&background=random",
		},
		uploadedAt: new Date(Date.now() - 3600000).toISOString(),
		likes: 25,
		downloads: 12,
		albumId: "2",
		fileSize: 2048000,
		fileType: "image/jpeg",
		width: 800,
		height: 600,
		isApproved: true,
	},
	{
		id: "2",
		slug: "photo-2",
		url: "https://picsum.photos/800/600?random=2",
		thumbnailUrl: "https://picsum.photos/400/300?random=2",
		title: "Reception Entrance",
		tags: ["reception", "entrance", "party"],
		uploadedBy: {
			id: "user-2",
			name: "Jane Smith",
			avatar: "https://ui-avatars.com/api/?name=Jane+Smith&background=random",
		},
		uploadedAt: new Date(Date.now() - 7200000).toISOString(),
		likes: 18,
		downloads: 8,
		albumId: "2",
		fileSize: 1856000,
		fileType: "image/jpeg",
		width: 800,
		height: 600,
		isApproved: true,
	},
	{
		id: "3",
		slug: "photo-3",
		url: "https://picsum.photos/800/600?random=3",
		thumbnailUrl: "https://picsum.photos/400/300?random=3",
		title: "First Dance",
		tags: ["dancing", "first-dance", "romantic"],
		uploadedBy: {
			id: "user-3",
			name: "Mike Johnson",
			avatar: "https://ui-avatars.com/api/?name=Mike+Johnson&background=random",
		},
		uploadedAt: new Date(Date.now() - 10800000).toISOString(),
		likes: 32,
		downloads: 15,
		albumId: "2",
		fileSize: 2200000,
		fileType: "image/jpeg",
		width: 800,
		height: 600,
		isApproved: false,
	},
	{
		id: "4",
		slug: "photo-4",
		url: "https://picsum.photos/800/600?random=4",
		thumbnailUrl: "https://picsum.photos/400/300?random=4",
		title: "Cake Cutting",
		tags: ["cake", "celebration", "sweet"],
		uploadedBy: {
			id: "user-1",
			name: "John Doe",
			avatar: "https://ui-avatars.com/api/?name=John+Doe&background=random",
		},
		uploadedAt: new Date(Date.now() - 14400000).toISOString(),
		likes: 15,
		downloads: 6,
		albumId: "2",
		fileSize: 1980000,
		fileType: "image/jpeg",
		width: 800,
		height: 600,
		isApproved: true,
	},
	{
		id: "5",
		slug: "photo-5",
		url: "https://picsum.photos/800/600?random=5",
		thumbnailUrl: "https://picsum.photos/400/300?random=5",
		title: "Guest Dancing",
		tags: ["dancing", "guests", "party", "fun"],
		uploadedBy: {
			id: "user-4",
			name: "Sarah Wilson",
			avatar: "https://ui-avatars.com/api/?name=Sarah+Wilson&background=random",
		},
		uploadedAt: new Date(Date.now() - 18000000).toISOString(),
		likes: 28,
		downloads: 11,
		albumId: "2",
		fileSize: 2100000,
		fileType: "image/jpeg",
		width: 800,
		height: 600,
		isApproved: true,
	},
	{
		id: "6",
		slug: "photo-6",
		url: "https://picsum.photos/800/600?random=6",
		thumbnailUrl: "https://picsum.photos/400/300?random=6",
		title: "Bouquet Toss",
		tags: ["bouquet", "tradition", "fun"],
		uploadedBy: {
			id: "user-2",
			name: "Jane Smith",
			avatar: "https://ui-avatars.com/api/?name=Jane+Smith&background=random",
		},
		uploadedAt: new Date(Date.now() - 21600000).toISOString(),
		likes: 22,
		downloads: 9,
		albumId: "2",
		fileSize: 1920000,
		fileType: "image/jpeg",
		width: 800,
		height: 600,
		isApproved: true,
	},
	{
		id: "7",
		slug: "photo-7",
		url: "https://picsum.photos/800/600?random=7",
		thumbnailUrl: "https://picsum.photos/400/300?random=7",
		title: "Wedding Party",
		tags: ["wedding-party", "bridesmaids", "groomsmen"],
		uploadedBy: {
			id: "user-5",
			name: "David Brown",
			avatar: "https://ui-avatars.com/api/?name=David+Brown&background=random",
		},
		uploadedAt: new Date(Date.now() - 25200000).toISOString(),
		likes: 35,
		downloads: 18,
		albumId: "2",
		fileSize: 2300000,
		fileType: "image/jpeg",
		width: 800,
		height: 600,
		isApproved: true,
	},
	{
		id: "8",
		slug: "photo-8",
		url: "https://picsum.photos/800/600?random=8",
		thumbnailUrl: "https://picsum.photos/400/300?random=8",
		title: "Reception Setup",
		tags: ["setup", "decorations", "venue"],
		uploadedBy: {
			id: "user-3",
			name: "Mike Johnson",
			avatar: "https://ui-avatars.com/api/?name=Mike+Johnson&background=random",
		},
		uploadedAt: new Date(Date.now() - 28800000).toISOString(),
		likes: 12,
		downloads: 4,
		albumId: "2",
		fileSize: 1750000,
		fileType: "image/jpeg",
		width: 800,
		height: 600,
		isApproved: true,
	},
];

export const MOCK_STATS: MediaCenterStats = {
	totalPhotos: 247,
	totalVideos: 12,
	totalAlbums: 8,
	totalSubAlbums: 1,
	totalLikes: 1250,
	totalDownloads: 450,
	storageUsed: "2.4 GB",
};

export const MOCK_CONTRIBUTORS: MediaCenterContributor[] = [
	{
		id: "user-1",
		name: "Harper Clark",
		email: "harper.clark@example.com",
		avatar: "https://ui-avatars.com/api/?name=Harper+Clark&background=random",
		photoCount: 23,
		videoCount: 3,
	},
	{
		id: "user-2",
		name: "David King",
		email: "david.king@example.com",
		avatar: "https://ui-avatars.com/api/?name=David+King&background=random",
		photoCount: 0,
		videoCount: 0,
	},
	{
		id: "user-3",
		name: "David Sanchez",
		email: "david.sanchez@example.com",
		avatar: "https://ui-avatars.com/api/?name=David+Sanchez&background=random",
		photoCount: 15,
		videoCount: 1,
	},
	{
		id: "user-4",
		name: "Harper Miller",
		email: "harper.miller@example.com",
		avatar: "https://ui-avatars.com/api/?name=Harper+Miller&background=random",
		photoCount: 0,
		videoCount: 0,
	},
	{
		id: "user-5",
		name: "James Martinez",
		email: "james.martinez@example.com",
		avatar: "https://ui-avatars.com/api/?name=James+Martinez&background=random",
		photoCount: 7,
		videoCount: 1,
	},
];

export const MOCK_LIVE_FEED_PHOTOS: LiveFeedPhoto[] = [
	{
		id: "1",
		url: "https://picsum.photos/800/600?random=1",
		thumbnailUrl: "https://picsum.photos/400/300?random=1",
		uploadedBy: {
			id: "user-1",
			name: "Sarah M.",
			avatar: "https://ui-avatars.com/api/?name=Sarah+M&background=random",
		},
		uploadedAt: new Date(Date.now() - 120000).toISOString(), // 2 minutes ago
		category: "Reception",
		likes: 8,
		comments: 2,
		isNew: true,
		tags: ["reception", "celebration"],
	},
	{
		id: "2",
		url: "https://picsum.photos/800/600?random=2",
		thumbnailUrl: "https://picsum.photos/400/300?random=2",
		uploadedBy: {
			id: "user-2",
			name: "Mike R.",
			avatar: "https://ui-avatars.com/api/?name=Mike+R&background=random",
		},
		uploadedAt: new Date(Date.now() - 300000).toISOString(), // 5 minutes ago
		category: "Activities",
		likes: 12,
		comments: 4,
		isNew: false,
		tags: ["activities", "workshop"],
	},
	{
		id: "3",
		url: "https://picsum.photos/800/600?random=3",
		thumbnailUrl: "https://picsum.photos/400/300?random=3",
		uploadedBy: {
			id: "user-3",
			name: "Emma K.",
			avatar: "https://ui-avatars.com/api/?name=Emma+K&background=random",
		},
		uploadedAt: new Date(Date.now() - 480000).toISOString(), // 8 minutes ago
		category: "Venue",
		likes: 15,
		comments: 6,
		isNew: false,
		tags: ["venue", "architecture"],
	},
];

export const MOCK_PHOTO_BOOTH_PHOTOS: PhotoBoothPhoto[] = [
	{
		id: "1",
		url: "https://picsum.photos/400/400?random=10",
		filter: "vintage",
		frame: "classic",
		timestamp: new Date(Date.now() - 600000).toISOString(),
	},
	{
		id: "2",
		url: "https://picsum.photos/400/400?random=11",
		filter: "glamour",
		frame: "elegant",
		timestamp: new Date(Date.now() - 1200000).toISOString(),
	},
	{
		id: "3",
		url: "https://picsum.photos/400/400?random=12",
		filter: "bw",
		frame: "none",
		timestamp: new Date(Date.now() - 1800000).toISOString(),
	},
];
