# Stage 1

FROM python:3-slim AS build-env

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt --target=/app/deps

# Stage 2

FROM gcr.io/distroless/python3-debian12

WORKDIR /app

COPY --from=build-env /app/deps /app/deps

COPY --from=build-env /app /app

ENV PYTHONPATH="/app/deps"

EXPOSE 80

CMD ["run.py"]
