import { Images } from "@/lib/lib-images";
import { Videos } from "@/lib/lib-videos";
export type MockEventData = {
  name: string;
  startDate: string;
  locationMap: string;
  price: number;
  featured?: boolean;
  category?: string;
  imageUrl: string;
  videoUrl?: string;
  slug?: string;
  username?: string;
  userProfilePicture?: string;
  latitude?: number;
  longitude?: number;
};

export const TECHNOLOGY_EVENTS = [
  {
    name: "Technology Event 1",
    startDate: "October 5, 2025",
    locationMap: "Barcelona Center",
    price: 123.42,
    featured: false,
    category: "Technology",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "technology-event-1",
    username: "Emma Anderson",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 41.35936586100186,
    longitude: 2.183908864294342,
  },
  {
    name: "Technology Event 2",
    startDate: "August 12, 2025",
    locationMap: "Dubai Center",
    price: 228.68,
    featured: false,
    category: "Technology",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "technology-event-2",
    username: "Ethan Lee",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 25.290623805766625,
    longitude: 55.2549556416191,
  },
  {
    name: "Technology Event 1",
    startDate: "October 5, 2025",
    locationMap: "Barcelona Center",
    price: 123.42,
    featured: false,
    category: "Technology",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "technology-event-1",
    username: "Emma Anderson",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 41.35936586100186,
    longitude: 2.183908864294342,
  },
  {
    name: "Technology Event 2",
    startDate: "August 12, 2025",
    locationMap: "Dubai Center",
    price: 228.68,
    featured: false,
    category: "Technology",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "technology-event-2",
    username: "Ethan Lee",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 25.290623805766625,
    longitude: 55.2549556416191,
  },
  {
    name: "Technology Event 2",
    startDate: "August 12, 2025",
    locationMap: "Dubai Center",
    price: 228.68,
    featured: false,
    category: "Technology",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "technology-event-2",
    username: "Ethan Lee",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 25.290623805766625,
    longitude: 55.2549556416191,
  },
  {
    name: "Technology Event 1",
    startDate: "October 5, 2025",
    locationMap: "Barcelona Center",
    price: 123.42,
    featured: false,
    category: "Technology",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "technology-event-1",
    username: "Emma Anderson",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 41.35936586100186,
    longitude: 2.183908864294342,
  },
];

export const MUSIC_EVENTS = [
  {
    name: "Music Event 1",
    startDate: "Jan 7, 2026",
    locationMap: "New York Center",
    price: 42.78,
    featured: true,
    category: "Music",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "music-event-1",
    username: "Alexander Taylor",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 40.672542196647626,
    longitude: -74.02935829658293,
  },
  {
    name: "Music Event 1",
    startDate: "July 12, 2025",
    locationMap: "New York Center",
    price: 42.78,
    featured: true,
    category: "Music",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "music-event-1",
    username: "Alexander Taylor",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 40.672542196647626,
    longitude: -74.02935829658293,
  },
  {
    name: "Music Event 1",
    startDate: "July 12, 2025",
    locationMap: "New York Center",
    price: 42.78,
    featured: true,
    category: "Music",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "music-event-1",
    username: "Alexander Taylor",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 40.672542196647626,
    longitude: -74.02935829658293,
  },
  {
    name: "Music Event 1",
    startDate: "Jan 9, 2026",
    locationMap: "New York Center",
    price: 42.78,
    featured: true,
    category: "Music",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "music-event-1",
    username: "Alexander Taylor",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 40.672542196647626,
    longitude: -74.02935829658293,
  },
  {
    name: "Music Event 1",
    startDate: "July 12, 2025",
    locationMap: "New York Center",
    price: 42.78,
    featured: true,
    category: "Music",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "music-event-1",
    username: "Alexander Taylor",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 40.672542196647626,
    longitude: -74.02935829658293,
  },
];

export const FOOD__DRINK_EVENTS = [
  {
    name: "Food & Drink Event 1",
    startDate: "September 11, 2025",
    locationMap: "San Francisco Center",
    price: 37.65,
    featured: false,
    category: "Food & Drink",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "food-&-drink-event-1",
    username: "Ava Lee",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 37.72810532381778,
    longitude: -122.46309399662594,
  },
  {
    name: "Food & Drink Event 2",
    startDate: "Jan 19, 2026",
    locationMap: "Rome Center",
    price: 132.98,
    featured: false,
    category: "Food & Drink",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "food-&-drink-event-2",
    username: "Evelyn Martinez",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 41.91299586396231,
    longitude: 12.54269316350947,
  },
  {
    name: "Food & Drink Event 2",
    startDate: "September 22, 2025",
    locationMap: "Rome Center",
    price: 132.98,
    featured: false,
    category: "Food & Drink",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "food-&-drink-event-2",
    username: "Evelyn Martinez",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 41.91299586396231,
    longitude: 12.54269316350947,
  },
  {
    name: "Food & Drink Event 2",
    startDate: "September 22, 2025",
    locationMap: "Rome Center",
    price: 132.98,
    featured: false,
    category: "Food & Drink",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "food-&-drink-event-2",
    username: "Evelyn Martinez",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 41.91299586396231,
    longitude: 12.54269316350947,
  },
  {
    name: "Food & Drink Event 2",
    startDate: "September 22, 2025",
    locationMap: "Rome Center",
    price: 132.98,
    featured: false,
    category: "Food & Drink",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "food-&-drink-event-2",
    username: "Evelyn Martinez",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 41.91299586396231,
    longitude: 12.54269316350947,
  },
];

export const ART__CULTURE_EVENTS = [
  {
    name: "Art & Culture Event 1",
    startDate: "June 26, 2025",
    locationMap: "Mexico City Center",
    price: 33.22,
    featured: false,
    category: "Art & Culture",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "art-&-culture-event-1",
    username: "Emma Martinez",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 19.449273653133822,
    longitude: -99.13356402553012,
  },
  {
    name: "Art & Culture Event 2",
    startDate: "October 2, 2025",
    locationMap: "Sydney Center",
    price: 95.79,
    featured: true,
    category: "Art & Culture",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "art-&-culture-event-2",
    username: "Mia Lee",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: -33.89746178213864,
    longitude: 151.19355705122078,
  },
  {
    name: "Art & Culture Event 1",
    startDate: "June 26, 2025",
    locationMap: "Mexico City Center",
    price: 33.22,
    featured: false,
    category: "Art & Culture",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "art-&-culture-event-1",
    username: "Emma Martinez",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 19.449273653133822,
    longitude: -99.13356402553012,
  },
  {
    name: "Art & Culture Event 2",
    startDate: "October 2, 2025",
    locationMap: "Sydney Center",
    price: 95.79,
    featured: true,
    category: "Art & Culture",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "art-&-culture-event-2",
    username: "Mia Lee",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: -33.89746178213864,
    longitude: 151.19355705122078,
  },
  {
    name: "Art & Culture Event 1",
    startDate: "June 26, 2025",
    locationMap: "Mexico City Center",
    price: 33.22,
    featured: false,
    category: "Art & Culture",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "art-&-culture-event-1",
    username: "Emma Martinez",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 19.449273653133822,
    longitude: -99.13356402553012,
  },
  {
    name: "Art & Culture Event 2",
    startDate: "October 2, 2025",
    locationMap: "Sydney Center",
    price: 95.79,
    featured: true,
    category: "Art & Culture",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "art-&-culture-event-2",
    username: "Mia Lee",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: -33.89746178213864,
    longitude: 151.19355705122078,
  },
];

export const BUSINESS_EVENTS = [
  {
    name: "Business Event 1",
    startDate: "June 3, 2025",
    locationMap: "Bangkok Center",
    price: 70.92,
    featured: false,
    category: "Business",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "business-event-1",
    username: "Emma Davis",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 13.78503184973354,
    longitude: 100.456261590793,
  },
  {
    name: "Business Event 1",
    startDate: "June 3, 2025",
    locationMap: "Bangkok Center",
    price: 70.92,
    featured: false,
    category: "Business",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "business-event-1",
    username: "Emma Davis",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 13.78503184973354,
    longitude: 100.456261590793,
  },
  {
    name: "Business Event 1",
    startDate: "June 3, 2025",
    locationMap: "Bangkok Center",
    price: 70.92,
    featured: false,
    category: "Business",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "business-event-1",
    username: "Emma Davis",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 13.78503184973354,
    longitude: 100.456261590793,
  },
  {
    name: "Business Event 1",
    startDate: "June 3, 2025",
    locationMap: "Bangkok Center",
    price: 70.92,
    featured: false,
    category: "Business",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "business-event-1",
    username: "Emma Davis",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 13.78503184973354,
    longitude: 100.456261590793,
  },
  {
    name: "Business Event 1",
    startDate: "June 3, 2025",
    locationMap: "Bangkok Center",
    price: 70.92,
    featured: false,
    category: "Business",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "business-event-1",
    username: "Emma Davis",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 13.78503184973354,
    longitude: 100.456261590793,
  },
  {
    name: "Business Event 1",
    startDate: "June 3, 2025",
    locationMap: "Bangkok Center",
    price: 70.92,
    featured: false,
    category: "Business",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "business-event-1",
    username: "Emma Davis",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 13.78503184973354,
    longitude: 100.456261590793,
  },
  {
    name: "Business Event 1",
    startDate: "June 3, 2025",
    locationMap: "Bangkok Center",
    price: 70.92,
    featured: false,
    category: "Business",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "business-event-1",
    username: "Emma Davis",
    userProfilePicture: Images?.asset?.user?.clark,
    latitude: 13.78503184973354,
    longitude: 100.456261590793,
  },
];

export const SPORTS_EVENTS = [
  {
    name: "Sports Event 1",
    startDate: "November 21, 2025",
    locationMap: "Bangkok Center",
    price: 204.51,
    featured: true,
    category: "Sports",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "sports-event-1",
    username: "Olivia Anderson",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 13.729347169713977,
    longitude: 100.45514073073674,
  },
  {
    name: "Sports Event 2",
    startDate: "August 15, 2025",
    locationMap: "Istanbul Center",
    price: 25.07,
    featured: false,
    category: "Sports",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "sports-event-2",
    username: "Alexander Brown",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 41.00401894063188,
    longitude: 29.008225588176085,
  },
  {
    name: "Sports Event 1",
    startDate: "November 21, 2025",
    locationMap: "Bangkok Center",
    price: 204.51,
    featured: true,
    category: "Sports",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "sports-event-1",
    username: "Olivia Anderson",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 13.729347169713977,
    longitude: 100.45514073073674,
  },
  {
    name: "Sports Event 2",
    startDate: "August 15, 2025",
    locationMap: "Istanbul Center",
    price: 25.07,
    featured: false,
    category: "Sports",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "sports-event-2",
    username: "Alexander Brown",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 41.00401894063188,
    longitude: 29.008225588176085,
  },
  {
    name: "Sports Event 1",
    startDate: "November 21, 2025",
    locationMap: "Bangkok Center",
    price: 204.51,
    featured: true,
    category: "Sports",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "sports-event-1",
    username: "Olivia Anderson",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 13.729347169713977,
    longitude: 100.45514073073674,
  },
  {
    name: "Sports Event 2",
    startDate: "August 15, 2025",
    locationMap: "Istanbul Center",
    price: 25.07,
    featured: false,
    category: "Sports",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "sports-event-2",
    username: "Alexander Brown",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 41.00401894063188,
    longitude: 29.008225588176085,
  },
];

export const ENTERTAINMENT_EVENTS = [
  {
    name: "Entertainment Event 1",
    startDate: "August 26, 2025",
    locationMap: "Los Angeles Center",
    price: 20.1,
    featured: false,
    category: "Entertainment",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "entertainment-event-1",
    username: "Noah Taylor",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 34.04648006082856,
    longitude: -118.2063885024697,
  },
  {
    name: "Entertainment Event 2",
    startDate: "November 16, 2025",
    locationMap: "Bangkok Center",
    price: 172.82,
    featured: false,
    category: "Entertainment",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "entertainment-event-2",
    username: "Elijah Davis",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 13.750396139915027,
    longitude: 100.53753452067882,
  },
  {
    name: "Entertainment Event 1",
    startDate: "August 26, 2025",
    locationMap: "Los Angeles Center",
    price: 20.1,
    featured: false,
    category: "Entertainment",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "entertainment-event-1",
    username: "Noah Taylor",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 34.04648006082856,
    longitude: -118.2063885024697,
  },
  {
    name: "Entertainment Event 2",
    startDate: "November 16, 2025",
    locationMap: "Bangkok Center",
    price: 172.82,
    featured: false,
    category: "Entertainment",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "entertainment-event-2",
    username: "Elijah Davis",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 13.750396139915027,
    longitude: 100.53753452067882,
  },
  {
    name: "Entertainment Event 1",
    startDate: "August 26, 2025",
    locationMap: "Los Angeles Center",
    price: 20.1,
    featured: false,
    category: "Entertainment",
    imageUrl: Images?.asset?.page?.background,
    videoUrl: Videos.heroBackground,
    slug: "entertainment-event-1",
    username: "Noah Taylor",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 34.04648006082856,
    longitude: -118.2063885024697,
  },
  {
    name: "Entertainment Event 2",
    startDate: "November 16, 2025",
    locationMap: "Bangkok Center",
    price: 172.82,
    featured: false,
    category: "Entertainment",
    imageUrl: Images?.asset?.page?.guest,
    videoUrl: Videos.heroBackground,
    slug: "entertainment-event-2",
    username: "Elijah Davis",
    userProfilePicture: Images?.asset?.user?.charlie,
    latitude: 13.750396139915027,
    longitude: 100.53753452067882,
  },
];

export const MOCK_EVENTS_PATIAL = [
  ...MUSIC_EVENTS,
  ...TECHNOLOGY_EVENTS,
  ...FOOD__DRINK_EVENTS,
  ...ART__CULTURE_EVENTS,
  ...BUSINESS_EVENTS,
  ...SPORTS_EVENTS,
  ...ENTERTAINMENT_EVENTS,
];
