export const mockVendors = [
  {
    id: 'vendor_1',
    businessName: 'Tasty Tacos Food Truck',
    category: 'Food - Mexican',
    email: 'contact@tastytacos.com',
    phone: '555-0101',
    rating: 4.8,
  },
  {
    id: 'vendor_2',
    businessName: 'Sweet Dreams Ice Cream',
    category: 'Food - Desserts',
    email: 'hello@sweetdreamsicecream.com',
    phone: '555-0102',
    rating: 4.9,
  },
  {
    id: 'vendor_3',
    businessName: 'Craft Coffee Co',
    category: 'Food - Beverages',
    email: 'info@craftcoffeeco.com',
    phone: '555-0103',
    rating: 4.7,
  },
  {
    id: 'vendor_4',
    businessName: 'Artisan Jewelry Studio',
    category: 'Retail - Jewelry',
    email: 'hello@artisanjewelry.com',
    phone: '555-0104',
    rating: 4.6,
  },
  {
    id: 'vendor_5',
    businessName: 'Green Garden Nursery',
    category: 'Retail - Plants',
    email: 'contact@greengarden.com',
    phone: '555-0105',
    rating: 4.8,
  },
  {
    id: 'vendor_6',
    businessName: 'Photo Booth Magic',
    category: 'Services - Photography',
    email: 'bookings@photoboothmagic.com',
    phone: '555-0106',
    rating: 4.9,
  },
  {
    id: 'vendor_7',
    businessName: 'Handmade Crafts Market',
    category: 'Retail - Crafts',
    email: 'shop@handmadecrafts.com',
    phone: '555-0107',
    rating: 4.5,
  },
  {
    id: 'vendor_8',
    businessName: 'BBQ Masters',
    category: 'Food - BBQ',
    email: 'orders@bbqmasters.com',
    phone: '555-0108',
    rating: 4.9,
  },
  {
    id: 'vendor_9',
    businessName: 'Vintage Clothing Co',
    category: 'Retail - Apparel',
    email: 'info@vintageclothing.com',
    phone: '555-0109',
    rating: 4.7,
  },
  {
    id: 'vendor_10',
    businessName: 'Kids Face Painting',
    category: 'Services - Entertainment',
    email: 'book@kidsfacepainting.com',
    phone: '555-0110',
    rating: 4.8,
  },
];
