import {
  Baby,
  BookOpen,
  Briefcase,
  Building,
  Camera,
  Gamepad2,
  GraduationCap,
  Heart,
  Mic,
  Monitor,
  Music,
  Palette,
  PartyPopper,
  Sparkles,
  Target,
  Trophy,
  Users,
  Zap,
} from "lucide-react";
import { ElementType } from "react";

export interface EventTypeOption {
  value: string;
  label: string;
  icon: ElementType;
  color: string;
  description: string;
  examples: string[];
  suggestedGuests: string;
  avgBudget: string;
  trending?: boolean;
  popular?: boolean;
  category: string;
  tags: string[];
}

export const eventCategories = [
  { id: "personal", name: "Personal & Family", color: "bg-pink-50" },
  { id: "business", name: "Business & Corporate", color: "bg-blue-50" },
  { id: "cultural", name: "Cultural & Arts", color: "bg-purple-50" },
  { id: "educational", name: "Educational & Training", color: "bg-green-50" },
  {
    id: "entertainment",
    name: "Entertainment & Recreation",
    color: "bg-orange-50",
  },
  { id: "community", name: "Community & Social", color: "bg-teal-50" },
];

export const predefinedEventTypes: EventTypeOption[] = [
  // Personal & Family
  {
    value: "Wedding",
    label: "Wedding",
    icon: Heart,
    color: "bg-pink-50 border-pink-200 hover:bg-pink-100",
    description: "Celebrate your special day",
    examples: [
      "Ceremony & Reception",
      "Intimate Garden Wedding",
      "Destination Wedding",
    ],
    suggestedGuests: "50-150 guests",
    avgBudget: "$15,000 - $50,000",
    trending: true,
    category: "personal",
    tags: ["ceremony", "celebration", "romantic", "formal"],
  },
  {
    value: "Birthday",
    label: "Birthday Party",
    icon: PartyPopper,
    color: "bg-yellow-50 border-yellow-200 hover:bg-yellow-100",
    description: "Celebrate another year of life",
    examples: ["Sweet 16", "30th Birthday Bash", "Kids Birthday Party"],
    suggestedGuests: "15-100 guests",
    avgBudget: "$500 - $5,000",
    popular: true,
    category: "personal",
    tags: ["celebration", "party", "milestone", "fun"],
  },
  {
    value: "Baby Shower",
    label: "Baby Shower",
    icon: Baby,
    color: "bg-blue-50 border-blue-200 hover:bg-blue-100",
    description: "Welcome the new arrival",
    examples: ["Gender Reveal", "Traditional Shower", "Sip & See"],
    suggestedGuests: "20-50 guests",
    avgBudget: "$300 - $1,500",
    category: "personal",
    tags: ["baby", "shower", "celebration", "family"],
  },
  {
    value: "Anniversary",
    label: "Anniversary",
    icon: Heart,
    color: "bg-rose-50 border-rose-200 hover:bg-rose-100",
    description: "Celebrate years together",
    examples: ["25th Silver", "50th Golden", "Vow Renewal"],
    suggestedGuests: "30-100 guests",
    avgBudget: "$1,000 - $10,000",
    category: "personal",
    tags: ["anniversary", "celebration", "romantic", "milestone"],
  },
  {
    value: "Graduation",
    label: "Graduation Party",
    icon: GraduationCap,
    color: "bg-indigo-50 border-indigo-200 hover:bg-indigo-100",
    description: "Honor academic achievements",
    examples: ["High School Grad", "College Celebration", "PhD Defense"],
    suggestedGuests: "25-75 guests",
    avgBudget: "$500 - $3,000",
    category: "personal",
    tags: ["graduation", "achievement", "celebration", "academic"],
  },
  {
    value: "Holiday Party",
    label: "Holiday Party",
    icon: Sparkles,
    color: "bg-emerald-50 border-emerald-200 hover:bg-emerald-100",
    description: "Seasonal celebrations",
    examples: ["Christmas Party", "New Year's Eve", "Halloween Bash"],
    suggestedGuests: "20-100 guests",
    avgBudget: "$400 - $2,500",
    category: "personal",
    tags: ["holiday", "seasonal", "party", "tradition"],
  },

  // Business & Corporate
  {
    value: "Corporate",
    label: "Corporate Event",
    icon: Building,
    color: "bg-slate-50 border-slate-200 hover:bg-slate-100",
    description: "Professional meetings & conferences",
    examples: ["Annual Conference", "Product Launch", "Team Building"],
    suggestedGuests: "25-500 guests",
    avgBudget: "$5,000 - $25,000",
    popular: true,
    category: "business",
    tags: ["corporate", "professional", "business", "networking"],
  },
  {
    value: "Conference",
    label: "Conference",
    icon: Briefcase,
    color: "bg-blue-50 border-blue-200 hover:bg-blue-100",
    description: "Large-scale professional gatherings",
    examples: ["Tech Conference", "Medical Summit", "Industry Convention"],
    suggestedGuests: "100-1000 guests",
    avgBudget: "$10,000 - $100,000",
    category: "business",
    tags: ["conference", "professional", "learning", "networking"],
  },
  {
    value: "Workshop",
    label: "Workshop",
    icon: BookOpen,
    color: "bg-green-50 border-green-200 hover:bg-green-100",
    description: "Interactive learning sessions",
    examples: ["Skills Training", "Creative Workshop", "Technical Bootcamp"],
    suggestedGuests: "10-50 guests",
    avgBudget: "$500 - $5,000",
    trending: true,
    category: "business",
    tags: ["workshop", "training", "skills", "hands-on"],
  },
  {
    value: "Networking",
    label: "Networking Event",
    icon: Users,
    color: "bg-cyan-50 border-cyan-200 hover:bg-cyan-100",
    description: "Professional connections",
    examples: ["Business Mixer", "Industry Meetup", "Speed Networking"],
    suggestedGuests: "30-150 guests",
    avgBudget: "$1,000 - $8,000",
    category: "business",
    tags: ["networking", "professional", "connections", "business"],
  },
  {
    value: "Product Launch",
    label: "Product Launch",
    icon: Zap,
    color: "bg-orange-50 border-orange-200 hover:bg-orange-100",
    description: "Showcase new products",
    examples: ["Tech Product Demo", "Fashion Launch", "App Release"],
    suggestedGuests: "50-200 guests",
    avgBudget: "$5,000 - $30,000",
    category: "business",
    tags: ["launch", "product", "demo", "marketing"],
  },
  {
    value: "Webinar",
    label: "Webinar",
    icon: Monitor,
    color: "bg-purple-50 border-purple-200 hover:bg-purple-100",
    description: "Online presentations",
    examples: ["Educational Webinar", "Product Demo", "Q&A Session"],
    suggestedGuests: "20-500 guests",
    avgBudget: "$200 - $2,000",
    category: "business",
    tags: ["webinar", "online", "presentation", "virtual"],
  },

  // Cultural & Arts
  {
    value: "Cultural",
    label: "Cultural Event",
    icon: Palette,
    color: "bg-purple-50 border-purple-200 hover:bg-purple-100",
    description: "Art shows & cultural celebrations",
    examples: [
      "Art Gallery Opening",
      "Cultural Festival",
      "Heritage Celebration",
    ],
    suggestedGuests: "30-200 guests",
    avgBudget: "$2,000 - $15,000",
    category: "cultural",
    tags: ["culture", "art", "heritage", "exhibition"],
  },
  {
    value: "Art Exhibition",
    label: "Art Exhibition",
    icon: Camera,
    color: "bg-pink-50 border-pink-200 hover:bg-pink-100",
    description: "Showcase artistic works",
    examples: ["Photography Show", "Sculpture Display", "Mixed Media"],
    suggestedGuests: "25-150 guests",
    avgBudget: "$1,500 - $10,000",
    category: "cultural",
    tags: ["art", "exhibition", "gallery", "creative"],
  },
  {
    value: "Concert",
    label: "Concert",
    icon: Mic,
    color: "bg-red-50 border-red-200 hover:bg-red-100",
    description: "Live musical performances",
    examples: ["Acoustic Concert", "Band Performance", "Classical Recital"],
    suggestedGuests: "50-500 guests",
    avgBudget: "$3,000 - $25,000",
    category: "cultural",
    tags: ["music", "concert", "performance", "live"],
  },
  {
    value: "Theater",
    label: "Theater Performance",
    icon: Users,
    color: "bg-violet-50 border-violet-200 hover:bg-violet-100",
    description: "Stage performances and plays",
    examples: ["Drama Performance", "Musical Theater", "Comedy Show"],
    suggestedGuests: "50-300 guests",
    avgBudget: "$2,000 - $15,000",
    category: "cultural",
    tags: ["theater", "performance", "stage", "drama"],
  },

  // Entertainment & Recreation
  {
    value: "Festival",
    label: "Festival",
    icon: Music,
    color: "bg-orange-50 border-orange-200 hover:bg-orange-100",
    description: "Music, food & entertainment",
    examples: ["Music Festival", "Food Fair", "Community Festival"],
    suggestedGuests: "200-5000 guests",
    avgBudget: "$20,000 - $200,000",
    trending: true,
    category: "entertainment",
    tags: ["festival", "music", "food", "entertainment"],
  },
  {
    value: "Sports Event",
    label: "Sports Event",
    icon: Trophy,
    color: "bg-green-50 border-green-200 hover:bg-green-100",
    description: "Athletic competitions",
    examples: ["Tournament", "Fun Run", "Sports Day"],
    suggestedGuests: "30-1000 guests",
    avgBudget: "$1,000 - $20,000",
    category: "entertainment",
    tags: ["sports", "competition", "athletic", "tournament"],
  },
  {
    value: "Gaming Event",
    label: "Gaming Event",
    icon: Gamepad2,
    color: "bg-cyan-50 border-cyan-200 hover:bg-cyan-100",
    description: "Video game competitions",
    examples: ["Esports Tournament", "Gaming Convention", "LAN Party"],
    suggestedGuests: "20-200 guests",
    avgBudget: "$1,000 - $10,000",
    trending: true,
    category: "entertainment",
    tags: ["gaming", "esports", "tournament", "competition"],
  },

  // Educational & Training
  {
    value: "Seminar",
    label: "Seminar",
    icon: BookOpen,
    color: "bg-blue-50 border-blue-200 hover:bg-blue-100",
    description: "Educational presentations",
    examples: ["Business Seminar", "Health Workshop", "Technology Talk"],
    suggestedGuests: "25-100 guests",
    avgBudget: "$1,000 - $5,000",
    category: "educational",
    tags: ["seminar", "education", "learning", "presentation"],
  },
  {
    value: "Training",
    label: "Training Session",
    icon: Target,
    color: "bg-emerald-50 border-emerald-200 hover:bg-emerald-100",
    description: "Skill development sessions",
    examples: ["Leadership Training", "Technical Training", "Safety Course"],
    suggestedGuests: "15-50 guests",
    avgBudget: "$800 - $4,000",
    category: "educational",
    tags: ["training", "skills", "development", "course"],
  },

  // Community & Social
  {
    value: "Charity",
    label: "Charity Gala",
    icon: Heart,
    color: "bg-emerald-50 border-emerald-200 hover:bg-emerald-100",
    description: "Fundraising events",
    examples: ["Fundraising Gala", "Charity Auction", "Awareness Campaign"],
    suggestedGuests: "100-500 guests",
    avgBudget: "$10,000 - $100,000",
    category: "community",
    tags: ["charity", "fundraising", "gala", "social impact"],
  },
  {
    value: "Community Meeting",
    label: "Community Meeting",
    icon: Users,
    color: "bg-teal-50 border-teal-200 hover:bg-teal-100",
    description: "Local community gatherings",
    examples: ["Town Hall", "Neighborhood Meeting", "Community Forum"],
    suggestedGuests: "20-100 guests",
    avgBudget: "$200 - $1,500",
    category: "community",
    tags: ["community", "meeting", "local", "discussion"],
  },
  {
    value: "Reunion",
    label: "Reunion",
    icon: Users,
    color: "bg-yellow-50 border-yellow-200 hover:bg-yellow-100",
    description: "Reconnect with old friends",
    examples: ["School Reunion", "Family Reunion", "Military Reunion"],
    suggestedGuests: "30-200 guests",
    avgBudget: "$2,000 - $15,000",
    category: "community",
    tags: ["reunion", "friends", "family", "reconnect"],
  },
];

export const customEventTypeSuggestions = [
  "Brunch Event",
  "Dinner Party",
  "Cocktail Hour",
  "Book Launch",
  "Fashion Show",
  "Film Screening",
  "Cooking Class",
  "Wine Tasting",
  "Awards Ceremony",
  "Retirement Party",
  "Housewarming",
  "Engagement Party",
  "Bridal Shower",
  "Bachelor Party",
  "Team Building",
  "Kickoff Meeting",
  "Board Meeting",
  "Investor Pitch",
  "Demo Day",
  "Hackathon",
  "Open House",
  "Volunteer Event",
  "Wellness Workshop",
  "Meditation Session",
  "Fitness Class",
  "Health Fair",
];
