export const Routes = {
  admin: {},
  web: {
    auth: {
      dashboardEventCreate: "/dashboard/event/create",
      dashboardEventDetail: "/dashboard/event/detail",
      dashboardSettings: "/dashboard/settings",
      dashboard: "/dashboard",
      dashboardOrganizerVerify: "/dashboard/organization/verify",
      dashboardEvents: "/dashboard/events",
      dashboardEventRsvp: "/rsvp",
      dashboardEventSeating: "/seating",
      dashboardEventAnnouncement: "/announcement",
      dashboardEventSurvey: "/survey",
      dashboardEventSchedule: "/schedule",
      dashboardEventTicket: "/ticket",
      dashboardEventMediaCenter: "/media-center",
      dashboardEventGames: "/games",
      dashboardEventGamesCreate: "/discover-games",
      dashboardEventGamesMyGames: "/my-games",
      dashboardEventGamesTrivia: "/trivia",
      dashboardEventGamesTriviaCustom: "/trivia-custom",
      dashboardEventGamesTapRace: "/tap-race",
      dashboardEventGamesTapRaceCustom: "/tap-race-custom",
      dashboardEventGamesScavengerHunt: "/scavenger-hunt",
      dashboardEventGamesScavengerHuntCustom: "/scavenger-hunt-custom",
      dashboardEventGamesCrowdPuzzle: "/crowd-puzzle",
      dashboardEventGamesCrowdPuzzleCustom: "/crowd-puzzle-custom",
      dashboardEventGamesDigitalBingo: "/digital-bingo",
      dashboardEventGamesDigitalBingoCustom: "/digital-bingo-custom",
      dashboardEventGamesPredictionMaster: "/prediction-master",
      dashboardEventGamesPredictionMasterCustom: "/prediction-master-custom",
      dashboardEventGamesBattleOfOpinions: "/battle-of-opinions",
      dashboardEventGamesBattleOfOpinionsCustom: "/battle-of-opinions-custom",
      dashboardEventGamesPuzzleRush: "/puzzle-rush",
      dashboardEventGamesPuzzleRushCustom: "/puzzle-rush-custom",
    },
    general: {
      home: "/",
      contact: "/contact",
      about: "/about",
      features: "/features",
      howItWorks: "/how-it-works",
      help: "/help",
      events: "/home/explore-events/location/New York",
      eventDetail: "/events",
      eventsCategory: "/events/category",
      organizers: "/organizers",
      forVendors: "/for-vendors",
    },
    guest: {
      signup: "/signup",
      signupEmailVerification: "/signup-email-verification",
      signin: "/signin",
      socialLoginResponse: "/social-login-response",

      forgotPasswordCheckEmail: "/forgot-password/check-email",
      forgotPasswordUpdatePassword: "/forgot-password/update-password",
    },
    vendor: {
      dashboard: "/vendor",
      profile: "/vendor/profile",
      signup: "/vendor/signup",
    },
  },
  api: {
    signup: "/auth/signup",
    signin: "/web/guest/signin",
    signupEmailVerification: "/auth/signup-email-verification",
    signupEmailVerificationResend: "/auth/signup-email-verification-resend",
    forgotPasswordCheckEmail: "/auth/forgot-password-check-email",
    forgotPasswordUpdatePassword: "/auth/forgot-password-update-password",
    userFetchUserAttribute: "/user/fetch-user-attributes",
  },
};
