import type { TimeSlot } from "./types";

export const mockCalendarData: TimeSlot[] = [
	{
		time: "09:00",
		label: "09:00",
		concurrentSessions: 1,
		density: "low",
		sessions: [
			{
				id: "s1",
				title: "Opening Keynote: The Future of AI",
				type: "keynote",
				track: "AI & Machine Learning",
				time: "09:00 - 10:00",
				location: "Main Hall",
				registered: 450,
				capacity: 500,
				status: "Available",
				speakers: ["Dr. Sarah Chen", "Prof. Michael Rodriguez"],
				description: "Join us for an inspiring keynote that explores the transformative potential of artificial intelligence in the next decade. This session will cover cutting-edge developments in AI, machine learning, and their real-world applications. Our expert speakers will discuss the future of AI technology, ethical considerations, and how organizations can prepare for the AI revolution. Whether you're a developer, business leader, or AI enthusiast, this keynote will provide valuable insights into the future of technology.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-purple-200 dark:border-purple-800",
					bg: "bg-purple-50 dark:bg-purple-900/20",
					darkBg: "dark:bg-purple-900/30",
					tagBg: "bg-purple-100",
					tagText: "text-purple-700",
					darkTagBg: "dark:bg-purple-800",
					darkTagText: "dark:text-purple-200",
					progress: "bg-purple-500",
				},
			},
		],
	},
	{
		time: "10:00",
		label: "10:00",
		concurrentSessions: 9,
		density: "high",
		sessions: [
			{
				id: "s2",
				title: "Coffee Break",
				type: "break",
				track: "General",
				time: "10:00 - 10:30",
				location: "Main Lobby",
				registered: 350,
				capacity: 500,
				status: "Available",
				speakers: ["Dr. Evelyn Reed"],
				description: "Take a well-deserved break and connect with fellow attendees, speakers, and industry professionals. This networking session provides the perfect opportunity to discuss ideas, exchange business cards, and build meaningful connections. Enjoy complimentary refreshments, coffee, and light snacks while engaging in conversations about the latest trends, challenges, and opportunities in technology. Don't miss this chance to expand your professional network and share experiences with peers from around the world.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-gray-200 dark:border-gray-700",
					bg: "bg-white dark:bg-gray-800",
					darkBg: "dark:bg-gray-900",
					tagBg: "bg-gray-100",
					tagText: "text-gray-700",
					darkTagBg: "dark:bg-gray-700",
					darkTagText: "dark:text-gray-200",
					progress: "bg-gray-500",
				},
			},
			{
				id: "s3",
				title: "Session 1: Deep Dive into DevOps",
				type: "workshop",
				track: "AI & Machine Learning",
				time: "10:00 - 11:30",
				location: "Main Hall",
				registered: 60,
				capacity: 59,
				status: "Full",
				speakers: ["Alex Johnson", "Dr. Sarah Chen"],
				description: "Dive deep into modern DevOps practices and automation strategies in this comprehensive workshop. Learn how to streamline your development workflow, implement CI/CD pipelines, and automate infrastructure management. Our expert instructors will cover containerization, orchestration tools, monitoring solutions, and best practices for building scalable, reliable systems. Through hands-on exercises and real-world case studies, you'll gain practical skills that you can immediately apply to your projects. Perfect for developers, DevOps engineers, and technical leads looking to modernize their development processes.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-blue-200 dark:border-blue-800",
					bg: "bg-white dark:bg-gray-800",
					darkBg: "dark:bg-gray-900",
					tagBg: "bg-blue-100",
					tagText: "text-blue-700",
					darkTagBg: "dark:bg-blue-800",
					darkTagText: "dark:text-blue-200",
					progress: "bg-blue-500",
				},
			},
			{
				id: "s4",
				title: "Session 2: Deep Dive into Cloud",
				type: "panel",
				track: "Cloud & DevOps",
				time: "10:00 - 11:30",
				location: "Room A",
				registered: 53,
				capacity: 66,
				status: "Almost Full",
				speakers: ["Prof. Michael Rodriguez"],
				description: "Join industry experts for an engaging panel discussion on cloud infrastructure and best practices. This session will explore the latest trends in cloud computing, including multi-cloud strategies, serverless architectures, and cloud-native development. Our panelists will share their experiences with major cloud providers, discuss cost optimization strategies, security considerations, and migration challenges. Whether you're just starting your cloud journey or looking to optimize existing infrastructure, this panel will provide valuable insights and practical advice from seasoned professionals.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-green-200 dark:border-green-800",
					bg: "bg-white dark:bg-gray-800",
					darkBg: "dark:bg-gray-900",
					tagBg: "bg-green-100",
					tagText: "text-green-700",
					darkTagBg: "dark:bg-green-800",
					darkTagText: "dark:text-green-200",
					progress: "bg-green-500",
				},
			},
			{
				id: "s5",
				title: "Session 3: Introduction to AI",
				type: "panel",
				track: "Security & Privacy",
				time: "10:00 - 11:30",
				location: "Room B",
				registered: 27,
				capacity: 49,
				status: "Available",
				speakers: ["Dr. Evelyn Reed"],
				description: "Perfect for beginners and those new to AI, this session provides a comprehensive introduction to artificial intelligence concepts and applications. Learn about the fundamentals of machine learning, neural networks, and deep learning in an accessible format. We'll explore real-world AI applications across various industries, from healthcare and finance to autonomous vehicles and natural language processing. The session will also cover the basics of AI ethics, bias, and responsible AI development. No prior AI experience required - just bring your curiosity and enthusiasm for learning about one of the most transformative technologies of our time.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-red-200 dark:border-red-800",
					bg: "bg-white dark:bg-gray-800",
					darkBg: "dark:bg-gray-900",
					tagBg: "bg-red-100",
					tagText: "text-red-700",
					darkTagBg: "dark:bg-red-800",
					darkTagText: "dark:text-red-200",
					progress: "bg-red-500",
				},
			},
			{
				id: "s6",
				title: "Lightning Talk: Edge AI",
				type: "session",
				track: "AI & Machine Learning",
				time: "10:00 - 10:20",
				location: "Breakout 1",
				registered: 45,
				capacity: 60,
				status: "Available",
				speakers: ["Dr. Sarah Chen"],
				description: "Get quick, actionable insights into edge computing and AI integration in this fast-paced lightning talk. Discover how edge AI is revolutionizing industries by bringing intelligence closer to data sources, reducing latency, and enabling real-time decision-making. We'll explore use cases in IoT, autonomous systems, and mobile applications, along with the technical challenges and solutions for deploying AI at the edge. This concise session is perfect for understanding the cutting-edge intersection of AI and edge computing.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-indigo-200 dark:border-indigo-800",
					bg: "bg-indigo-50 dark:bg-indigo-900/20",
					darkBg: "dark:bg-indigo-900/30",
					tagBg: "bg-indigo-100",
					tagText: "text-indigo-700",
					darkTagBg: "dark:bg-indigo-800",
					darkTagText: "dark:text-indigo-200",
					progress: "bg-indigo-500",
				},
			},
			{
				id: "s7",
				title: "Workshop: Terraform for Teams",
				type: "workshop",
				track: "Cloud & DevOps",
				time: "10:00 - 11:00",
				location: "Workshop Room B",
				registered: 32,
				capacity: 40,
				status: "Almost Full",
				speakers: ["Alex Johnson"],
				description: "Master infrastructure as code with Terraform in this hands-on workshop. Learn how to define, provision, and manage cloud infrastructure using declarative configuration files. We'll cover Terraform basics, state management, modules, and best practices for team collaboration. Through practical exercises, you'll create and deploy infrastructure to major cloud providers, understand how to manage complex multi-cloud environments, and learn techniques for maintaining infrastructure code. Bring your laptop and be ready to code - this interactive session will give you the skills to automate your infrastructure provisioning.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-emerald-200 dark:border-emerald-800",
					bg: "bg-emerald-50 dark:bg-emerald-900/20",
					darkBg: "dark:bg-emerald-900/30",
					tagBg: "bg-emerald-100",
					tagText: "text-emerald-700",
					darkTagBg: "dark:bg-emerald-800",
					darkTagText: "dark:text-emerald-200",
					progress: "bg-emerald-500",
				},
			},
			{
				id: "s8",
				title: "Panel: Diversity in Tech",
				type: "panel",
				track: "People & Culture",
				time: "10:00 - 11:00",
				location: "Room C",
				registered: 120,
				capacity: 150,
				status: "Available",
				speakers: ["Dr. Evelyn Reed", "Prof. Michael Rodriguez"],
				description: "Join an important discussion on building inclusive and diverse technology teams. This panel will explore strategies for creating welcoming work environments, implementing inclusive hiring practices, and fostering cultures where everyone can thrive. Our speakers will share real-world examples of successful diversity initiatives, discuss the business case for inclusion, and provide actionable steps for leaders and team members. We'll also address common challenges, unconscious bias, and how to create mentorship and growth opportunities for underrepresented groups in tech. This session is essential for anyone committed to making the tech industry more inclusive.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-pink-200 dark:border-pink-800",
					bg: "bg-pink-50 dark:bg-pink-900/20",
					darkBg: "dark:bg-pink-900/30",
					tagBg: "bg-pink-100",
					tagText: "text-pink-700",
					darkTagBg: "dark:bg-pink-800",
					darkTagText: "dark:text-pink-200",
					progress: "bg-pink-500",
				},
			},
			{
				id: "s9",
				title: "Hands-on: Intro to Docker",
				type: "workshop",
				track: "Cloud & DevOps",
				time: "10:00 - 11:30",
				location: "Lab 1",
				registered: 22,
				capacity: 25,
				status: "Almost Full",
				speakers: ["Alex Johnson"],
				description: "Learn containerization fundamentals with Docker in this beginner-friendly hands-on workshop. Discover how containers revolutionize application deployment by packaging applications with their dependencies. We'll cover Docker basics, including images, containers, Dockerfiles, and Docker Compose. Through practical exercises, you'll build, run, and manage containers, understand container networking and volumes, and learn how to optimize your Docker images. This session is perfect for developers and DevOps professionals looking to modernize their deployment workflows and gain hands-on experience with one of the most popular containerization platforms.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-yellow-200 dark:border-yellow-800",
					bg: "bg-yellow-50 dark:bg-yellow-900/20",
					darkBg: "dark:bg-yellow-900/30",
					tagBg: "bg-yellow-100",
					tagText: "text-yellow-700",
					darkTagBg: "dark:bg-yellow-800",
					darkTagText: "dark:text-yellow-200",
					progress: "bg-yellow-500",
				},
			},
		],
	},
	{
		time: "10:30",
		label: "10:30",
		concurrentSessions: 2,
		density: "low",
		sessions: [
			{
				id: "s6",
				title: "Building Scalable ML Pipelines",
				type: "workshop",
				track: "AI & Machine Learning",
				time: "10:30 - 12:00",
				location: "Workshop Room A",
				registered: 48,
				capacity: 50,
				status: "Full",
				speakers: ["Alex Johnson"],
				description: "Master the art of building production-ready machine learning pipelines in this intensive hands-on workshop. Learn how to transform experimental ML models into robust, scalable production systems. We'll cover data preprocessing, feature engineering, model training, validation, deployment strategies, and monitoring. Through real-world examples and hands-on exercises, you'll learn to use popular ML frameworks, implement MLOps practices, and understand how to handle model versioning, A/B testing, and continuous integration for ML systems. This workshop is ideal for data scientists and ML engineers ready to take their models from prototype to production.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-orange-200 dark:border-orange-800",
					bg: "bg-orange-50 dark:bg-orange-900/20",
					darkBg: "dark:bg-orange-900/30",
					tagBg: "bg-orange-100",
					tagText: "text-orange-700",
					darkTagBg: "dark:bg-orange-800",
					darkTagText: "dark:text-orange-200",
					progress: "bg-orange-500",
				},
			},
			{
				id: "s7",
				title: "Cloud Security Best Practices",
				type: "session",
				track: "Security & Privacy",
				time: "10:30 - 11:30",
				location: "Conference Room B",
				registered: 75,
				capacity: 100,
				status: "Available",
				speakers: ["Dr. Sarah Chen"],
				description: "Protect your cloud infrastructure with essential security practices in this comprehensive session. Learn about cloud security fundamentals, including identity and access management, network security, data encryption, and compliance requirements. We'll explore security best practices for major cloud providers, discuss common vulnerabilities and how to mitigate them, and cover incident response strategies. Through real-world case studies, you'll understand how to implement defense-in-depth strategies, conduct security audits, and maintain a strong security posture in cloud environments. This session is crucial for anyone responsible for cloud infrastructure security.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-blue-200 dark:border-blue-800",
					bg: "bg-blue-50 dark:bg-blue-900/20",
					darkBg: "dark:bg-blue-900/30",
					tagBg: "bg-blue-100",
					tagText: "text-blue-700",
					darkTagBg: "dark:bg-blue-800",
					darkTagText: "dark:text-blue-200",
					progress: "bg-blue-500",
				},
			},
		],
	},
	{
		time: "14:00",
		label: "14:00",
		concurrentSessions: 1,
		density: "low",
		sessions: [
			{
				id: "s8",
				title: "DevOps Panel Discussion",
				type: "panel",
				track: "Cloud & DevOps",
				time: "14:00 - 15:00",
				location: "Main Hall",
				registered: 180,
				capacity: 200,
				status: "Almost Full",
				speakers: ["Alex Johnson", "Prof. Michael Rodriguez", "Dr. Sarah Chen"],
				description: "Join a dynamic panel discussion with industry experts exploring the latest DevOps trends and future directions. Our panelists will share insights on emerging technologies, evolving best practices, and predictions for the future of software delivery. Topics will include GitOps, platform engineering, observability, security in DevOps (DevSecOps), and the impact of AI on development workflows. This interactive session will include audience Q&A, allowing you to get answers to your burning DevOps questions. Whether you're a seasoned practitioner or new to DevOps, you'll gain valuable perspectives on where the industry is heading and how to prepare for the future.",
				date: "Day 1 - Nov 4, 2025",
				colors: {
					border: "border-blue-200 dark:border-blue-800",
					bg: "bg-blue-50 dark:bg-blue-900/20",
					darkBg: "dark:bg-blue-900/30",
					tagBg: "bg-blue-100",
					tagText: "text-blue-700",
					darkTagBg: "dark:bg-blue-800",
					darkTagText: "dark:text-blue-200",
					progress: "bg-blue-500",
				},
			},
		],
	},
];

export default mockCalendarData;
